# Generated by Django 4.2.3 on 2023-11-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_is_blocked'),
        ('U_Admin', '0001_initial'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='offer_coupon',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
      
      
    ]
