# Generated by Django 4.2.3 on 2023-10-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_id',
        ),
    ]
