# Generated by Django 4.2.3 on 2023-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0003_remove_brand_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Section',
            new_name='section',
        ),
    ]
