# Generated by Django 4.2.3 on 2023-10-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0005_productimage_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='productconnection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='U_Admin.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='my-images'),
        ),
    ]
