# Generated by Django 4.2.3 on 2023-10-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0007_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='productconnection',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='U_Admin.productimage'),
        ),
    ]
