# Generated by Django 4.2.3 on 2023-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0010_alter_product_prod_pic_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_pic_three',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_pic_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
