# Generated by Django 4.2.3 on 2023-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Admin', '0012_brand_brand_img_section_section_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='small',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xl',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xxl',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xxxl',
            field=models.CharField(blank=True, null=True),
        ),
    ]
